### PR TITLE
Add 0.7 dependencies

### PR DESCRIPTION
**Pull request by utzcoz**
Google devices and Kernel need them.

### CODE REVIEW

**Comment by utzcoz** [comment]
cc @pdsouza .

**Review by pdsouza — APPROVED** [review]
Thanks for adding these @utzcoz !

**Comment by utzcoz** [comment]
@pdsouza Could you help to update the Docker Hub version? I can test it locally.

**Comment by pdsouza** [comment]
@utzcoz I pushed pdsouza/maruos to Docker Hub 👍

**Comment by pdsouza** [comment]
@utzcoz Also pushed the pdsouza/maruos-devbox image which depends on this as the base image

**Pull request merged**
